"""Générateur IPC-2581 — XML squelette valide (Content/Ecad/StepData/BOM/Layout/Avl)."""
from __future__ import annotations

import datetime as _dt
import math
import xml.dom.minidom as minidom
import xml.etree.ElementTree as ET
from typing import Any, Dict, List, Tuple

from shared.utilities import get_logger

log = get_logger(__name__)

_NS = "http://www.ipc-2581.org/schemas/2581"
_ETF_VERSION = "C"


def _sub(parent: ET.Element, tag: str, text: Any = None, **attrs: Any) -> ET.Element:
    el = ET.SubElement(parent, tag, {k: str(v) for k, v in attrs.items() if v is not None})
    if text is not None:
        el.text = str(text)
    return el


class IPC2581Generator:
    """Produit un document IPC-2581 (revision B/C) décrivant le design."""

    def __init__(self, graph: Any, supplier: str = "jlcpcb") -> None:
        self.graph = graph
        self.supplier = supplier

    def generate(self) -> str:
        """XML IPC-2581 pretty-printé."""
        root = ET.Element("IPC-2581", {
            "c": _ETF_VERSION, "revision": "B",
            "contentRole": "owner", "xmlns": _NS,
        })
        content = _sub(root, "Content")
        self._logistic_header(content)
        ecad = _sub(content, "Ecad", name=str(getattr(self.graph, "name", "pcb")))
        cad = _sub(ecad, "CadHeader")
        self._units(cad)
        self._layers(cad)
        self._stackup(cad)
        step = _sub(ecad, "StepData", id="PCB")
        self._bom(step)
        self._layout(step)
        self._avl(step)

        raw = ET.tostring(root, encoding="unicode")
        pretty = minidom.parseString(raw).toprettyxml(indent="  ")
        # supprime la ligne vide parasite après le prologue
        lines = [ln for ln in pretty.splitlines() if ln.strip()]
        log.info("IPC-2581 généré (%d composants)", len(self.graph.components))
        return "\n".join(lines) + "\n"

    # -- sections -----------------------------------------------------------------
    def _logistic_header(self, content: ET.Element) -> None:
        lh = _sub(content, "LogisticHeader")
        _sub(lh, "Rev", "A")
        _sub(lh, "Src", "PCB_AI_DESIGNER_V3")
        _sub(lh, "Supplier", self.supplier)
        _sub(lh, "CreationDate", _dt.datetime.now(_dt.timezone.utc).isoformat(timespec="seconds"))
        _sub(lh, "Note", "Generated by PCB_AI_DESIGNER_V3 exporter")

    def _units(self, cad: ET.Element) -> None:
        units = _sub(cad, "Units", unitsName="millimeter")
        _sub(units, "Value", 1.0)

    def _layers(self, cad: ET.Element) -> None:
        for i, layer in enumerate(list(getattr(self.graph, "layers", []) or [])):
            name = str(getattr(layer, "name", f"L{i}"))
            el = _sub(cad, "Layer", refDes=name,
                      layerFunction="SIGNAL" if name.endswith(".Cu") else "SIGNAL")
            _sub(el, "StepRef", id="PCB")

    def _stackup(self, cad: ET.Element) -> None:
        group = _sub(cad, "StackupGroup", name="Stackup", topContractLayer="F.Cu")
        _sub(group, "StackupLayer", name="F.Cu",
             thicknessUm=35.0, material="COPPER", layerType="SIGNAL")
        w, h = self._board_size()
        _sub(group, "BoardExtent", x1=0.0, y1=0.0, x2=w, y2=h)

    def _board_size(self) -> Tuple[float, float]:
        bs = getattr(self.graph, "board_size", (50.0, 40.0))
        if isinstance(bs, (tuple, list)) and len(bs) >= 2:
            return (float(bs[0]), float(bs[1]))
        return (50.0, 40.0)

    def _bom(self, step: ET.Element) -> None:
        bom = _sub(step, "Bom")
        groups: Dict[Tuple[str, str, str], List[str]] = {}
        for ref, comp in self.graph.components.items():
            key = (str(getattr(comp, "mpn", "") or ""),
                   str(getattr(comp, "value", "") or ""),
                   str(getattr(comp, "footprint", "") or ""))
            groups.setdefault(key, []).append(ref)
        for (mpn, value, footprint), refs in sorted(groups.items()):
            item = _sub(bom, "BomItem", qty=len(refs))
            _sub(item, "MPN", mpn or value or "N/A")
            _sub(item, "Description", f"{value} {footprint}".strip())
            for ref in sorted(refs):
                _sub(item, "RefDes", refDes=ref)

    def _layout(self, step: ET.Element) -> None:
        layout = _sub(step, "Layout")
        layers = [(i, str(getattr(l, "name", f"L{i}")))
                  for i, l in enumerate(list(getattr(self.graph, "layers", []) or []))]
        for index, lname in layers:
            lf = _sub(layout, "LayerFeature", refDes=lname, layerFunction="SIGNAL")
            for net_id in sorted(self.graph.nets):
                path = getattr(self.graph.nets[net_id], "path", None)
                if path is None:
                    continue
                if int(getattr(path, "layer", 0)) == index:
                    pts = list(getattr(path, "points", []) or [])
                    for i in range(len(pts) - 1):
                        _sub(lf, "Line", x1=round(pts[i].x, 6), y1=round(pts[i].y, 6),
                             x2=round(pts[i + 1].x, 6), y2=round(pts[i + 1].y, 6),
                             lineWidth=round(float(getattr(path, "width_mm", 0.2)), 6),
                             net=net_id)
                for via in (getattr(path, "vias", []) or []):
                    if index in (int(via[1]), int(via[2])):
                        _sub(lf, "Pad", x=round(float(via[0].x), 6),
                             y=round(float(via[0].y), 6), w=0.6, h=0.6, net=net_id)
            for ref in sorted(self.graph.components):
                comp = self.graph.components[ref]
                rot = math.radians(float(getattr(comp, "rotation", 0.0) or 0.0))
                c, s = math.cos(rot), math.sin(rot)
                for pad in list(getattr(comp, "pads", []) or []):
                    if int(getattr(pad, "layer", 0) or 0) != index:
                        continue
                    ax = float(comp.x) + float(pad.x) * c - float(pad.y) * s
                    ay = float(comp.y) + float(pad.x) * s + float(pad.y) * c
                    _sub(lf, "Pad", x=round(ax, 6), y=round(ay, 6),
                         w=round(float(pad.w), 6), h=round(float(pad.h), 6),
                         net=str(getattr(pad, "net_id", "") or ""),
                         refDes=ref, name=str(getattr(pad, "name", "")))

    def _avl(self, step: ET.Element) -> None:
        avl = _sub(step, "Avl")
        seen: List[str] = []
        for comp in self.graph.components.values():
            mpn = str(getattr(comp, "mpn", "") or "")
            if mpn and mpn not in seen:
                seen.append(mpn)
        for mpn in sorted(seen):
            item = _sub(avl, "Item")
            _sub(item, "MPN", mpn)
            _sub(item, "Manufacturer", "generic")
            _sub(item, "AVLRef", mpn)
