apiVersion: v1
kind: Service
metadata:
  name: pcb3-api-svc
  namespace: pcb-ai-v3
  labels:
    app.kubernetes.io/name: pcb-ai-designer
    app.kubernetes.io/component: api
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: pcb-ai-designer
    app.kubernetes.io/component: api
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      protocol: TCP
